sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env:
        - CS_CHECK=true
        - TEST_COVERAGE=true
        - PHPSTAN=true
    - php: nightly
      env:
        - CS_CHECK=false
        - TEST_COVERAGE=false
        - PHPSTAN=false

before_install:
- if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
- travis_retry composer self-update

install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
- stty cols 120
- export COLUMNS=120
- composer show

script:
- if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage && composer test-infection ; else composer test ; fi
- if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
- if [[ $PHPSTAN == 'true' ]]; then composer phpstan ; fi

after_script:
- if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: false

env:
  global:
    secure: K7FyIxMVJc/Vf+nEjNkoCyp3/54ibwAssMEkB64/qF85Oq1M6GQJA+HOW3EfkSaDD4LwtFmBL5x1JcIsxNW6xeA2QY92cJLoLj0AR2oGSo/WOLo83is/s86NcIfy5SrBZsYMPkrMCnk6dcmqVzSe3XeFBickeX+fAQ/xeEDAORMFZ/cF+0BB2/fm1QE+Embi+J1qor/y8LP/U0BVTiHJ/G+ym8VCyhKSrUT2qxIgprsNu3t/jlrck4FpNfS0Ri35ct/jdyzwKsCLKe1C3yMssUoZNNRAudCqbTPc70Wdz2qzYckUznRo9DfhurSfwdt6KfTAB3sgP4o4NY6mBBUQ+qe/0txxMCiri9Z9RcTYn+bj6nxY0fLfOVVL+UxglnhnJsETJ40LS1b7TG0Nnxpngv3EGhjL+UMfWSL+7lOm3MyHt5gmmephuov9BdD3wmWElFwrF3a+J0B0+b3pdh1wCgtcxHYPzZ0AcCsIKGZI/hDQ8oXYSZuNjEWDXDWxk9urhfnx6hU1a5nGyOn9ZwDig6RU4tF1DthAnqrzUDdGQo0YbrTNJnczjRpuyWkBHUyszCmyIbzwuQDXXc4S8PnOi7yJ7Y5UrRC7169FWbcFBu61y/CpzOlRIUmT4k5lkeVB3aDcbQ9aAjPQfKvqEjcXNY6Jmmux6dXSZqxTXwS+G8k=
